### ISSUE TITLE
Proposal: Reduce Pipeline.map's IPC overhead with chunking

### ISSUE THREAD

**Issue by LennartGevers** [pipefunc/pipefunc#484]
Hi @basnijholt,
I've been using `pipefunc` on a scientific computing workflow and have been so far quite impressed by how much simpler my codebase became and the overall developer experience of pipefunc in general.
Thanks for you work!

I ran into the problem that `mapspec` introduced quite a lot of overhead for some `PipeFunc`s which compute much faster than the overhead introduced by for instance `ProcessPoolExecutor.submit()`.  However, performing these computations manually with `ProcessPoolExecutor.map()` **with an adequate chunksize** is rather performant, as chunking the inputs minimizes IPC 
(running `ProcessPoolExecutor.map(chunksize=1)` leads to a similar performance loss.)

Unfortunately, the current implementation of `Pipeline.map()` with `mapspec` does not allow a similar optimization (without custom parallelization) and each `mapspec` computation (each index) results in a `Executor.submit()` call, while `mapspec` computations of the same `PipeFunc` with a large set of inputs could be easily batched just like its done in `ProcessPoolExecutor.map()` for instance.

As I did not want to resort to custom parallelization within a `PipeFunc` in this scenario, I am currently implementing a chunksize option to `Pipeline.map()` on my [fork](https://github.com/LennartGevers/pipefunc) of `pipefunc` which allows the user to specify chunksizes for different `Pipefunc`s, similar to specifying different `Executor` instances. 

Internally I have modified the `_run_iteration_and_process()` function to handle lists of indexes instead of a single index and added some prior index batching in `_maybe_parallel_map` and unpack the result array after calling `_result()` on the `concurrent.futures.Future` instance.

```python
def _run_iteration_and_process(
    index_chunk: list[int],
    func: PipeFunc,
    kwargs: dict[str, Any],
    shape: tuple[int, ...],
    shape_mask: tuple[bool, ...],
    arrays: Sequence[StorageBase],
    cache: _CacheBase | None = None,
    *,
    force_dump: bool = False,
) -> list[tuple[Any, ...]]:

    chunk_outputs = []

    for index in index_chunk:
        selected = _select_kwargs_and_eval_resources(
            func, kwargs, shape, shape_mask, index
        )
        output = _run_iteration(func, selected, cache)
        outputs = _pick_output(func, output)
        _update_array(
            func,
            arrays,
            shape,
            shape_mask,
            index,
            outputs,
            in_post_process=False,
            force_dump=force_dump,
        )
        chunk_outputs.append(outputs)
    return chunk_outputs
```

On the simple benchmark below I achieved a performance increase from about 85 seconds to 0.3 seconds for the total runtime of `Pipeline.map()` on my machine running Python 3.11.2 (Setting chunksize=1 results in about the same behaviour as currently implemented in `pipefunc`).
I am using the same chunksize that is implemented in `multiprocessing.Pool.map()` as the default chunksize. 

```python
def sample_function(x: float) -> float:
    return x**3

samples = np.random.randint(0, 100, 10**5)

sample_function_node = PipeFunc(
    sample_function, "sample_result", mapspec="x[i] -> sample_result[i]"
)
sample_pipeline = Pipeline([sample_function_node])

with ProcessPoolExecutor() as ex:
    chunksize, extra = divmod(len(samples), ex._max_workers * 4)
    if extra:
        chunksize += 1

    with Timer(f"Pipeline[chunksize={chunksize}]"):
        sample_pipeline.map(
            dict(x=samples),
            executor=ex,
            output_names=["sample_result"],
            storage="dict",
            chunksizes={"sample_result": chunksize},
        )

    with Timer(f"Pipeline[chunksize={1}]"):
        sample_pipeline.map(
            dict(x=samples),
            executor=ex,
            output_names=["sample_result"],
            storage="dict",
            chunksizes={"sample_result": 1},
        )


```

Just give me a heads-up if you are interested in adding this enhancement to pipefunc so that I can prepare a PR or whether you have other plans for parallelization that would conflict with this solution.

**Comment by basnijholt** [comment]
> I've been using pipefunc on a scientific computing workflow and have been so far quite impressed by how much simpler my codebase became and the overall developer experience of pipefunc in general.

@LennartGevers, that is awesome! Could I ask how you found out about PipeFunc? I want to get it in the hands of more folks! 😄 


About the chunksize, that is a very good idea! It was already on the very long list of improvements I still want to make at some point. I would very much appreciate if you could help out and make a PR! :tada: 🚀 

I also find it satisfying that you have been able to make this change relatively easily, which means my effort to make the code maintainable/understandable worthwhile.

**Comment by LennartGevers** [comment]
@basnijholt, I've found out about `pipefunc` through this [reddit post](https://www.reddit.com/r/Python/comments/1gp79mj/pipefunc_structure_automate_and_simplify_your/?utm_source=share&utm_medium=mweb3x&utm_name=mweb3xcss&utm_term=1&utm_content=share_button). I was at that time looking for a pipeline framework for a python backend at wortk but found `pipefunc` to be well suited for my bachelors thesis project. It was actually quite pleasant to make the changes in your codebase, it does seem quite understandable😄.

I will setup a proper dev environment for pipefunc and do the remaining integration and some unittesting of this feature. Perhaps you have an idea how this option should be expose by `Pipeline.map()` to the user? Otherwise I would stick to the chunksizes dictionary, which takes an integer or maybe also a callable for each PipeFunc, simmilar to the executor option.

**Comment by basnijholt** [comment]
>through this [reddit post](https://www.reddit.com/r/Python/comments/1gp79mj/pipefunc_structure_automate_and_simplify_your/?utm_source=share&utm_medium=mweb3x&utm_name=mweb3xcss&utm_term=1&utm_content=share_button)

Good to know! Will post it to Reddit at some low frequency 😄 

> how this option should be expose by Pipeline.map() to the user

I think a dict with chunksizes from `output_name` -> `int` makes sense! 

> dev environment

Setting up a dev env should be as simple as `pip install -e ".[dev]"`


Thanks again!

**Comment by basnijholt** [comment]
@LennartGevers [did just that](https://www.reddit.com/r/Python/comments/1hk85dp/pipefunc_build_lightningfast_pipelines_with/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) ;)

**Comment by LennartGevers** [comment]
> @LennartGevers [did just that](https://www.reddit.com/r/Python/comments/1hk85dp/pipefunc_build_lightningfast_pipelines_with/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) ;)

Looks good! I'll let you know if I stumble upon some places where you could also make some promo for pipefunc 😄
